# Update repository traffic graph every day at midnight

name: Repository Traffic
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Traffic
        uses: wumphlett/repostats@v2.0.1
        with:
          commit_msg: "Updating repository traffic graph"
          format_readme: true
        env:
          TRAFFIC_ACTION_TOKEN: ${{ secrets.TRAFFIC_ACTION_TOKEN }}
          
